name: Run SedStart Test

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedinqa/sedstart@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY }}
          project_id: 
          test_id: 
          profile_id: 
          browser: 
          headless: 
          environment: 
